//
// Created by asus on 8/25/2026.
//

#ifndef HOTELRESERVATIONSYSTEM_LOG_MESSAGE_STATUS_H
#define HOTELRESERVATIONSYSTEM_LOG_MESSAGE_STATUS_H

enum class LogMessageType{
    BOOKING,
    CANCELLATION,
    CHECK_IN,
    CHECK_OUT,
    BILLING
};

#endif //HOTELRESERVATIONSYSTEM_LOG_MESSAGE_STATUS_H