//
// Created by asus on 8/24/2026.
//

#ifndef HOTELRESERVATIONSYSTEM_RESERVATIONSTATUS_H
#define HOTELRESERVATIONSYSTEM_RESERVATIONSTATUS_H

enum class ReservationStatus{
    RESERVED,
    CHECKED_IN,
    CHECKED_OUT,
    CANCELLED
 };

#endif //HOTELRESERVATIONSYSTEM_RESERVATIONSTATUS_H